[pytest]
addopts = --import-mode=importlib

pythonpath =
    backend
    components/language-analysis/src
    components/behavioural-tracking/src
    components/physiological-analysis/src
    components/facial-analysis/src

testpaths =
    backend/tests
    components/language-analysis/tests
    components/behavioural-tracking/tests
    components/physiological-analysis/tests
    components/facial-analysis/tests
