[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "j26-language-analysis"
version = "0.1.0"
description = "J26-IT-402 language analysis component"
requires-python = ">=3.10,<3.14"
dependencies = [
    "nltk>=3.9,<4.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]